---
- name: Install Kubernetes Cluster
  hosts: k8s
  become: true
  gather_facts: false
  tasks:
    - name: Upgrade all packages
      yum:
        name: "*"
        state: latest
    
    - name: Install a list of packages with a list variable
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - git
        - vim
        - net-tools
        - wget
        - curl

    - name: Rename the systems
      shell:
         hostnamectl set-hostname k8smaster

    - name: Install Docker app
      shell:
        curl -fsSL https://get.docker.com | bash
      ignore_errors: true
...